// scripts/deploy.js
// ─────────────────────────────────────────────────────────────────────────────
// Deploys MedicinalPlantRegistry (which inherits RoleManager + BatchTransfer).
// Usage:
//   Local  → npx hardhat run scripts/deploy.js --network localhost
//   Sepolia → npx hardhat run scripts/deploy.js --network sepolia
// ─────────────────────────────────────────────────────────────────────────────

const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  // Print deployer info
  const [deployer] = await ethers.getSigners();
  console.log("\n========================================");
  console.log("  MediChain — Contract Deployment");
  console.log("========================================");
  console.log(`  Deployer : ${deployer.address}`);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`  Balance  : ${ethers.formatEther(balance)} ETH`);
  console.log("----------------------------------------\n");

  // Deploy MedicinalPlantRegistry
  console.log("Deploying MedicinalPlantRegistry...");
  const Registry = await ethers.getContractFactory("MedicinalPlantRegistry");
  const registry = await Registry.deploy();
  await registry.waitForDeployment();

  const contractAddress = await registry.getAddress();
  console.log(`  ✔ MedicinalPlantRegistry deployed at: ${contractAddress}\n`);

  // ── Auto-assign deployer as Farmer for quick testing ─────────────────
  console.log("Assigning deployer the 'Farmer' role for local testing...");
  const tx = await registry.assignRole(deployer.address, "Farmer");
  await tx.wait();
  console.log("  ✔ Role 'Farmer' assigned to deployer\n");

  // ── Export deployment info ────────────────────────────────────────────
  await exportDeploymentInfo(registry, contractAddress);

  console.log("========================================");
  console.log("  Deployment complete!");
  console.log("========================================\n");
}

/**
 * Writes contract address + ABI to:
 *   blockchain/deployments/deployment.json
 *   ../src/contractConfig.js   ← ready to use in React
 */
async function exportDeploymentInfo(contract, contractAddress) {
  // Build ABI from artifact
  const artifact = require("../artifacts/contracts/MedicinalPlantRegistry.sol/MedicinalPlantRegistry.json");
  const abi = artifact.abi;

  // ── Write deployment.json ─────────────────────────────────────────
  const deploymentsDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(deploymentsDir)) fs.mkdirSync(deploymentsDir);

  const deploymentInfo = {
    contractName: "MedicinalPlantRegistry",
    contractAddress,
    deployedAt: new Date().toISOString(),
    network: (await contract.runner.provider.getNetwork()).name,
    abi,
  };

  const jsonPath = path.join(deploymentsDir, "deployment.json");
  fs.writeFileSync(jsonPath, JSON.stringify(deploymentInfo, null, 2));
  console.log(`  ✔ Deployment info saved to  blockchain/deployments/deployment.json`);

  // ── Write ../src/contractConfig.js for React ──────────────────────
  // Also copy the raw artifact JSON to frontend/src/abi/ for direct import
  const abiDir = path.join(__dirname, "../../frontend/src/abi");
  if (!fs.existsSync(abiDir)) fs.mkdirSync(abiDir, { recursive: true });
  const artifactSrc  = path.join(__dirname, "../artifacts/contracts/MedicinalPlantRegistry.sol/MedicinalPlantRegistry.json");
  const artifactDest = path.join(abiDir, "MedicinalPlantRegistry.json");
  fs.copyFileSync(artifactSrc, artifactDest);
  console.log(`  ✔ ABI artifact copied to      frontend/src/abi/MedicinalPlantRegistry.json`);

  const reactConfigPath = path.join(__dirname, "../../frontend/src/contractConfig.js");
  const jsContent = `// Auto-generated by blockchain/scripts/deploy.js — DO NOT EDIT MANUALLY
// Last deployed: ${new Date().toISOString()}

export const contractAddress = "${contractAddress}";

export const contractABI = ${JSON.stringify(abi, null, 2)};
`;
  fs.writeFileSync(reactConfigPath, jsContent);
  console.log(`  ✔ React config saved to      frontend/src/contractConfig.js\n`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
