// scripts/export-abi.js
// ─────────────────────────────────────────────────────────────────────────────
// Standalone script to re-export the ABI + address from an existing
// deployments/deployment.json into src/contractConfig.js without redeploying.
//
// Usage: npx hardhat run scripts/export-abi.js
// ─────────────────────────────────────────────────────────────────────────────

const fs   = require("fs");
const path = require("path");

async function main() {
  const deploymentPath = path.join(__dirname, "../deployments/deployment.json");

  if (!fs.existsSync(deploymentPath)) {
    console.error(
      "Error: blockchain/deployments/deployment.json not found.\n" +
      "Run 'npm run deploy:local' or 'npm run deploy:sepolia' first."
    );
    process.exit(1);
  }

  const deployment = JSON.parse(fs.readFileSync(deploymentPath, "utf8"));
  const { contractAddress, abi, deployedAt, network } = deployment;

  console.log(`\nExporting ABI for MedicinalPlantRegistry`);
  console.log(`  Address   : ${contractAddress}`);
  console.log(`  Network   : ${network}`);
  console.log(`  Deployed  : ${deployedAt}\n`);

  const reactConfigPath = path.join(__dirname, "../../frontend/src/contractConfig.js");
  const abiDir = path.join(__dirname, "../../frontend/src/abi");
  if (!fs.existsSync(abiDir)) fs.mkdirSync(abiDir, { recursive: true });
  const artifactSrc  = path.join(__dirname, "../artifacts/contracts/MedicinalPlantRegistry.sol/MedicinalPlantRegistry.json");
  if (fs.existsSync(artifactSrc)) {
    fs.copyFileSync(artifactSrc, path.join(abiDir, "MedicinalPlantRegistry.json"));
    console.log(`  ✔ ABI artifact copied to      frontend/src/abi/MedicinalPlantRegistry.json`);
  }
  const jsContent = `// Auto-generated by blockchain/scripts/export-abi.js — DO NOT EDIT MANUALLY
// Contract  : MedicinalPlantRegistry
// Network   : ${network}
// Deployed  : ${deployedAt}

export const contractAddress = "${contractAddress}";

export const contractABI = ${JSON.stringify(abi, null, 2)};
`;

  fs.writeFileSync(reactConfigPath, jsContent);
  console.log(`  ✔ frontend/src/contractConfig.js updated successfully.`);
  console.log(`\nUpdate frontend/src/contract.js to import from contractConfig.js:\n`);
  console.log(`  import { contractAddress, contractABI } from "./contractConfig";`);
  console.log(`  // then use them in getContract() as before\n`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
